# Generated by Django 5.0 on 2025-09-20 20:20

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import tracker.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Launchpad",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("locality", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("launch_attempts", models.IntegerField(default=0)),
                ("launch_successes", models.IntegerField(default=0)),
                (
                    "status",
                    enumfields.fields.EnumField(
                        default="active",
                        enum=tracker.enums.LaunchpadStatus,
                        max_length=55,
                    ),
                ),
                ("details", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rocket",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("mass", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=False)),
                ("stages", models.IntegerField()),
                ("boosters", models.IntegerField(default=0)),
                ("success_rate_pct", models.IntegerField(default=0)),
                ("cost_per_launch", models.BigIntegerField()),
                ("first_flight", models.DateField()),
                (
                    "type",
                    enumfields.fields.EnumField(
                        enum=tracker.enums.RocketType, max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Launch",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("launch_datetime", models.DateTimeField()),
                ("upcoming", models.BooleanField()),
                ("success", models.BooleanField(blank=True, default=None, null=True)),
                ("details", models.TextField(blank=True, default="", null=True)),
                (
                    "launchpad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launches",
                        to="tracker.launchpad",
                    ),
                ),
                (
                    "rocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launches",
                        to="tracker.rocket",
                    ),
                ),
            ],
        ),
    ]
